#!/bin/bash

stty -icanon -echo

{
   echo -e "compiletoflash\n"
   cat ../common/conditional.txt
   cat ../common/disassembler-rv64im.txt
   cat ../common/dictionary-tools.txt
   cat save.txt
   echo -e "save\" mecrisp-quintus-linux-rv64im-with-disassembler\n"
   echo -e "bye\n"
   # cat -
} | qemu-riscv64-static mecrisp-quintus-linux-rv64im

{
   echo -e "compiletoflash\n"
   cat ../common/conditional.txt
   cat ../common/acrobatics.txt
   cat ../common/disassembler-rv64im.txt
   cat ../common/dictionary-tools.txt
   cat save.txt
   echo -e "save\" mecrisp-quintus-linux-rv64im-with-acrobatics-and-disassembler\n"
   echo -e "bye\n"
   # cat -
} | qemu-riscv64-static mecrisp-quintus-linux-rv64im

stty sane

echo -e ""
