#!/bin/bash

riscv64-linux-gnu-as -o mecrisp-quintus-linux-rv64im.o mecrisp-quintus-linux-rv64im.s -march=rv64im
riscv64-linux-gnu-ld -T mecrisp.ld -z max-page-size=4096 -o mecrisp-quintus-linux-rv64im mecrisp-quintus-linux-rv64im.o -m elf64lriscv
riscv64-linux-gnu-objdump -Mnumeric -D mecrisp-quintus-linux-rv64im > mecrisp-quintus-linux-rv64im.list
