#!/bin/bash

riscv64-linux-gnu-as -o mecrisp-quintus-linux-rv64imc.o mecrisp-quintus-linux-rv64imc.s -march=rv64im
riscv64-linux-gnu-ld -T mecrisp.ld -z max-page-size=4096 -o mecrisp-quintus-linux-rv64imc mecrisp-quintus-linux-rv64imc.o -m elf64lriscv
riscv64-linux-gnu-objdump -Mnumeric -D mecrisp-quintus-linux-rv64imc > mecrisp-quintus-linux-rv64imc.list
